"use client";

import { useState, useEffect } from "react";
import { Market } from "@/lib/types";
import { Link as LinkIcon, MapPin, ExternalLink, Plus, X, Calendar } from "lucide-react";

interface MarketFormProps {
    initialData?: Market;
    onSubmit: (data: {
        dates: Date[];
        marketName: string;
        location: string;
        mapsLink?: string;
        startTime: string;
        endTime: string;
        isActive: boolean;
    }) => Promise<void>;
    onCancel: () => void;
}

export default function MarketForm({ initialData, onSubmit, onCancel }: MarketFormProps) {
    const [loading, setLoading] = useState(false);
    const isEditMode = !!initialData;

    // Helper to generate link
    const generateMapsLink = (name: string, loc: string) => {
        const query = `${name} ${loc}`.trim();
        if (!query) return "";
        return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
    };

    // For new markets: array of dates. For edit: single date in array
    const [dates, setDates] = useState<string[]>(() => {
        if (initialData?.date) {
            return [new Date(initialData.date).toISOString().split("T")[0]];
        }
        return [""];
    });

    const [formData, setFormData] = useState({
        marketName: initialData?.marketName || "",
        location: initialData?.location || "",
        mapsLink: initialData?.mapsLink || "",
        startTime: initialData?.startTime || "",
        endTime: initialData?.endTime || "",
        isActive: initialData?.isActive ?? true,
    });

    // Effect to update mapsLink when marketName or location changes
    useEffect(() => {
        const isAutoGenerated = !formData.mapsLink || formData.mapsLink.includes("google.com/maps/search/?api=1&query=");

        if (isAutoGenerated) {
            const newLink = generateMapsLink(formData.marketName, formData.location);
            if (newLink !== formData.mapsLink) {
                setFormData(prev => ({ ...prev, mapsLink: newLink }));
            }
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [formData.marketName, formData.location]);

    const addDate = () => {
        setDates(prev => [...prev, ""]);
    };

    const removeDate = (index: number) => {
        if (dates.length > 1) {
            setDates(prev => prev.filter((_, i) => i !== index));
        }
    };

    const updateDate = (index: number, value: string) => {
        setDates(prev => prev.map((d, i) => i === index ? value : d));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);

        try {
            // Filter out empty dates and convert to Date objects
            const validDates = dates
                .filter(d => d.trim() !== "")
                .map(d => new Date(`${d}T12:00:00Z`));

            if (validDates.length === 0) {
                alert("Please add at least one date");
                setLoading(false);
                return;
            }

            await onSubmit({
                dates: validDates,
                marketName: formData.marketName,
                location: formData.location,
                mapsLink: formData.mapsLink,
                startTime: formData.startTime,
                endTime: formData.endTime,
                isActive: formData.isActive,
            });
        } finally {
            setLoading(false);
        }
    };

    return (
        <form onSubmit={handleSubmit} className="p-6 space-y-6">
            {/* ═══ DATES SECTION ═══ */}
            <div className="space-y-3">
                <div className="flex items-center justify-between">
                    <label className="text-xs uppercase tracking-widest font-bold text-dipiu-coffee flex items-center gap-2">
                        <Calendar className="w-3.5 h-3.5" />
                        {isEditMode ? "Date" : "Dates"}
                    </label>
                    {!isEditMode && (
                        <button
                            type="button"
                            onClick={addDate}
                            className="flex items-center gap-1 text-[10px] uppercase tracking-wider font-bold text-dipiu-red hover:text-dipiu-coffee transition-colors"
                        >
                            <Plus className="w-3.5 h-3.5" />
                            Add Date
                        </button>
                    )}
                </div>

                <div className="space-y-2">
                    {dates.map((date, index) => (
                        <div key={index} className="flex items-center gap-2 group">
                            <div className="relative flex-1">
                                <input
                                    type="date"
                                    value={date}
                                    onChange={(e) => updateDate(index, e.target.value)}
                                    required
                                    className="w-full bg-white border border-dipiu-coffee/10 rounded-xl px-4 py-3 focus:border-dipiu-red focus:ring-2 focus:ring-dipiu-red/10 focus:outline-none transition-all text-dipiu-coffee shadow-sm"
                                />
                            </div>
                            {!isEditMode && dates.length > 1 && (
                                <button
                                    type="button"
                                    onClick={() => removeDate(index)}
                                    className="p-2.5 text-dipiu-coffee/30 hover:text-red-500 hover:bg-red-50 rounded-xl transition-all opacity-0 group-hover:opacity-100"
                                >
                                    <X className="w-4 h-4" />
                                </button>
                            )}
                        </div>
                    ))}
                </div>

                {!isEditMode && dates.length > 1 && (
                    <p className="text-[10px] text-dipiu-coffee/40 ml-1">
                        {dates.filter(d => d).length} date{dates.filter(d => d).length !== 1 ? 's' : ''} selected — each will create a separate market entry
                    </p>
                )}
            </div>

            {/* Elegant Divider */}
            <div className="h-px bg-gradient-to-r from-transparent via-dipiu-coffee/10 to-transparent" />

            {/* ═══ MARKET DETAILS ═══ */}
            <div className="space-y-4">
                {/* Market Name */}
                <div className="space-y-2">
                    <label className="text-xs uppercase tracking-widest font-bold text-dipiu-coffee">
                        Market Name
                    </label>
                    <input
                        type="text"
                        value={formData.marketName}
                        onChange={(e) => setFormData(prev => ({ ...prev, marketName: e.target.value }))}
                        placeholder="e.g. Redcliffe Markets"
                        required
                        className="w-full bg-white border border-dipiu-coffee/10 rounded-xl px-4 py-3 focus:border-dipiu-red focus:ring-2 focus:ring-dipiu-red/10 focus:outline-none transition-all text-dipiu-coffee shadow-sm placeholder:text-dipiu-coffee/30"
                    />
                </div>

                {/* Location */}
                <div className="space-y-2">
                    <label className="text-xs uppercase tracking-widest font-bold text-dipiu-coffee">
                        Location
                    </label>
                    <div className="relative">
                        <input
                            type="text"
                            value={formData.location}
                            onChange={(e) => setFormData(prev => ({ ...prev, location: e.target.value }))}
                            placeholder="e.g. Redcliffe Parade"
                            required
                            className="w-full bg-white border border-dipiu-coffee/10 rounded-xl pl-10 pr-4 py-3 focus:border-dipiu-red focus:ring-2 focus:ring-dipiu-red/10 focus:outline-none transition-all text-dipiu-coffee shadow-sm placeholder:text-dipiu-coffee/30"
                        />
                        <MapPin className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-dipiu-coffee/30" />
                    </div>
                </div>

                {/* Maps Link */}
                <div className="space-y-2">
                    <div className="flex items-center justify-between">
                        <label className="text-xs uppercase tracking-widest font-bold text-dipiu-coffee">
                            Maps Link
                        </label>
                        {formData.mapsLink && (
                            <a
                                href={formData.mapsLink}
                                target="_blank"
                                rel="noreferrer"
                                className="flex items-center gap-1 text-[10px] text-dipiu-red hover:underline"
                            >
                                Preview <ExternalLink className="w-2.5 h-2.5" />
                            </a>
                        )}
                    </div>
                    <div className="relative">
                        <input
                            type="url"
                            value={formData.mapsLink}
                            onChange={(e) => setFormData(prev => ({ ...prev, mapsLink: e.target.value }))}
                            placeholder="Auto-generated or paste custom URL"
                            className="w-full bg-dipiu-beige/50 border border-dipiu-coffee/10 rounded-xl pl-10 pr-4 py-3 focus:border-dipiu-red focus:ring-2 focus:ring-dipiu-red/10 focus:outline-none transition-all text-dipiu-coffee/70 text-sm shadow-sm placeholder:text-dipiu-coffee/30"
                        />
                        <LinkIcon className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-dipiu-coffee/30" />
                    </div>
                </div>
            </div>

            {/* Elegant Divider */}
            <div className="h-px bg-gradient-to-r from-transparent via-dipiu-coffee/10 to-transparent" />

            {/* ═══ TIME RANGE ═══ */}
            <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                    <label className="text-xs uppercase tracking-widest font-bold text-dipiu-coffee">
                        Start Time
                    </label>
                    <input
                        type="text"
                        value={formData.startTime}
                        onChange={(e) => setFormData(prev => ({ ...prev, startTime: e.target.value }))}
                        placeholder="e.g. 8am"
                        required
                        className="w-full bg-white border border-dipiu-coffee/10 rounded-xl px-4 py-3 focus:border-dipiu-red focus:ring-2 focus:ring-dipiu-red/10 focus:outline-none transition-all text-dipiu-coffee shadow-sm placeholder:text-dipiu-coffee/30"
                    />
                </div>
                <div className="space-y-2">
                    <label className="text-xs uppercase tracking-widest font-bold text-dipiu-coffee">
                        End Time
                    </label>
                    <input
                        type="text"
                        value={formData.endTime}
                        onChange={(e) => setFormData(prev => ({ ...prev, endTime: e.target.value }))}
                        placeholder="e.g. 2pm"
                        required
                        className="w-full bg-white border border-dipiu-coffee/10 rounded-xl px-4 py-3 focus:border-dipiu-red focus:ring-2 focus:ring-dipiu-red/10 focus:outline-none transition-all text-dipiu-coffee shadow-sm placeholder:text-dipiu-coffee/30"
                    />
                </div>
            </div>

            {/* ═══ ACTIVE TOGGLE ═══ */}
            <div className="flex items-center justify-between p-4 bg-dipiu-beige/30 rounded-xl border border-dipiu-coffee/5">
                <div>
                    <p className="text-sm font-medium text-dipiu-coffee">Visibility</p>
                    <p className="text-[11px] text-dipiu-coffee/50">
                        {formData.isActive ? "Visible on the public website" : "Hidden from visitors"}
                    </p>
                </div>
                <button
                    type="button"
                    onClick={() => setFormData(prev => ({ ...prev, isActive: !prev.isActive }))}
                    className={`
                        relative w-14 h-7 rounded-full transition-all duration-300 shadow-inner
                        ${formData.isActive ? "bg-dipiu-red" : "bg-dipiu-coffee/20"}
                    `}
                >
                    <span
                        className={`
                            absolute top-1 w-5 h-5 bg-white rounded-full transition-all duration-300 shadow-md
                            ${formData.isActive ? "right-1" : "left-1"}
                        `}
                    />
                </button>
            </div>

            {/* ═══ ACTIONS ═══ */}
            <div className="flex gap-3 pt-2">
                <button
                    type="button"
                    onClick={onCancel}
                    disabled={loading}
                    className="flex-1 bg-dipiu-coffee/5 text-dipiu-coffee font-medium text-sm py-3.5 rounded-xl hover:bg-dipiu-coffee/10 transition-all duration-300 disabled:opacity-50"
                >
                    Cancel
                </button>
                <button
                    type="submit"
                    disabled={loading}
                    className="flex-1 bg-dipiu-red text-white font-medium text-sm py-3.5 rounded-xl hover:bg-dipiu-coffee transition-all duration-300 disabled:opacity-50 flex items-center justify-center gap-2 shadow-lg shadow-dipiu-red/20"
                >
                    {loading ? (
                        <>
                            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                            Saving...
                        </>
                    ) : (
                        isEditMode ? "Save Changes" : `Add ${dates.filter(d => d).length || 1} Market${dates.filter(d => d).length > 1 ? 's' : ''}`
                    )}
                </button>
            </div>
        </form>
    );
}
